### PR TITLE
Allow override of active mouse button.

### PR DESCRIPTION
**Pull request by trattles**
Hey awesome hook - apologies if this doesn't fit the contribution guidelines.

I just needed to be able to override the scroll from left, to middle click - and I thought it was a pretty easy addition, though perhaps it could be a bit more robust.

### CODE REVIEW

**Comment by rfmiotto** [comment]
Hi @trattles,

Thank you very much for your contribution!
Sorry if it took me so long to respond. I was very busy last week.

I will merge your commit and also publish a new version of the package. Just to let other users know about this feature, could you also put a brief explanation in the README file?

Thanks again for your contribution!

**Review by rfmiotto — CHANGES_REQUESTED** [review]
Hi @trattles,

If you don't mind, before I merge, could you please write your code as follows:
It is just a Prettier fix.

```javascript
  const getIsMousePressActive = (buttonsCode: number) => {
    return (
      (activeMouseButton === "Left" && buttonsCode === 1) ||
      (activeMouseButton === "Middle" && buttonsCode === 4) ||
      (activeMouseButton === "Right" && buttonsCode === 2)
    );
  };
```

**Comment by trattles** [comment]
> Hi @trattles,
> 
> If you don't mind, before I merge, could you please write your code as follows: It is just a Prettier fix.
> 
> ```js
>   const getIsMousePressActive = (buttonsCode: number) => {
>     return (
>       (activeMouseButton === "Left" && buttonsCode === 1) ||
>       (activeMouseButton === "Middle" && buttonsCode === 4) ||
>       (activeMouseButton === "Right" && buttonsCode === 2)
>     );
>   };
> ```

Absolutely :)

I updated as per prettier, as well as updated the readme to describe the option.

**Comment by rfmiotto** [comment]
Thank you very much, @trattles 

I have just published a new version of the package (0.4.4) with your changes.

All the best

**Pull request merged**
