### PR TITLE
Feat/drag sensitivity

### LINKED ISSUE #2: [Feature request] Sensitivity to start drag
Hi there, thanks for having created this component. We just started using it and it is very simple and straightforward to use, plus it does not interfere with other events passing through the same scroll container, which is great.  
To the actual question:

Scenario:  
User clicks/taps on some element included in scroll container, in order to perform some action on it. 
It is relatively easy for her/him to actually move mouse a little while still keeping mouse button clicked (or finger pressed). Basically it is easy to start an unwanted drag operation.
When mouse button/finger is released, a short unnoticeable drag operation has happened, but no click has happened. _Correctly_ IMHO, the click event is "captured" by the drag operation and thus not passed to other components. 

Would it be possible to add a sensitivity input parameter, e.g. expressed in pixels or in a time duration? So that:
- when mouse move events arrive after mouse down, and minimum scrolling distance/time has not passed, the actual drag and scroll operation is not actually performed
- _case A)_ when further mouse events arrive and threshold is overcome, the drag and scroll operation kicks in and so scroll position "catches up" to where it should have been
- _case B)_ when instead a mouse up event arrives with threshold not overcome, drag and scroll operation has never actually started and is aborted. Instead, and here lies the detail, mouse up event is propagated, so to allow click detection by other handlers.

Does this makes sense?

We were looking and main library `index.ts` file, I guess conceptually this feature introduces an additional state in the state machine. Now there are 2 of them: is not dragging / is dragging. With such feature there would be 3: is not dragging / waiting for threshold / is dragging.

We could submit a PR too, if you could provide some explanation on the main gist of code.

Thanks anyway

### PR DESCRIPTION
**Pull request by BrainCrumbz**
See issue #2 for discussion. Closes #2

### CODE REVIEW

**Comment by rfmiotto** [comment]
Dear Giuseppe,

Thank you very much for your valuable contribution and time.

If it's not too much to ask, could you just do a few lint (Prettier) tweaks before the merge?

In the src/index.tsx file, could you please use the code below? Prettier made some (minor) changes.

```typescript
type OptionsType = {
   decayRate?: number;
   safeDisplacement?: number;
};

type ReturnType = {
   events: {
     onMouseDown: (e: React.MouseEvent<HTMLElement>) => void;
   };
};

export function useDraggable(
   ref: MutableRefObject<HTMLElement>,
   { decayRate = 0.95, safeDisplacement = 10 }: OptionsType = {}
): ReturnType {
   const internalState = useRef({
```

Thanks

**Comment by BrainCrumbz** [comment]
No probs, actually it was me mixing commas instead of semicolons.

**Comment by BrainCrumbz** [comment]
@rfmiotto how does it work with new releases? Do you have a timeline? Or you push a new version when you have a new feature (like this case)? 
Sorry we were not able to figure out how that works.

**Comment by rfmiotto** [comment]
Hi @BrainCrumbz,

I released the updated version of the package on NPM under version 0.3.0 yesterday. Did you manage to upgrade it with npm?

As I implemented this hook all at once, I didn't plan any versioning policies. So far, I'm publishing new releases manually after some feature is included (as in this case). I still need to set up a GitHub Actions for this. Would you have any suggestions? If you think it's worth doing something to improve this issue of new versions, please let me know. I will be happy to take steps to improve the code.

All the best

**Comment by BrainCrumbz** [comment]
Thanks for the new version. No suggestion about those topics you mention: actually your choice seems quite reasonable at the moment. We'll grab the updated version in these coming days, and let you know if anything funny arises, but I think it'll go smoothly.  
Kind regards

**Comment by rfmiotto** [comment]
Hi @BrainCrumbz,

I would like to inform you that a new version (0.4.0) has been released that includes an elastic effect when the user tries to scroll beyond the allowed area. There is no breaking change compared to the version you worked on (0.3.0). Feel free to give me feedback on this new feature.

Best regards

**Comment by BrainCrumbz** [comment]
Cool! Thanks for the heads up!

**Pull request merged**
